export const jails = [
    { name: "Santa Rita Jail", county: "Alameda" },
    { name: "Amador County Jail", county: "Amador" },
    { name: "Butte County Jail", county: "Butte" },
    { name: "Calaveras County Adult Detention Facility", county: "Calaveras" },
    { name: "Colusa County Jail", county: "Colusa" },
    { name: "Marsh Creek Detention Facility", county: "Contra Costa" },
    { name: "Martinez Detention Facility", county: "Contra Costa" },
    { name: "West County Detention Facility", county: "Contra Costa" },
    { name: "Del Norte County Jail", county: "Del Norte" },
    { name: "El Dorado County Jail, Placerville", county: "El Dorado" },
    { name: "El Dorado County Jail, South Lake Tahoe", county: "El Dorado" },
    { name: "Fresno County Main Jail", county: "Fresno" },
    { name: "Fresno North Annex Jail", county: "Fresno" },
    { name: "Fresno South Annex Jail", county: "Fresno" },
    { name: "Glenn County Adult Detention Facility", county: "Glenn" },
    { name: "Humboldt County Correctional Facility", county: "Humboldt" },
    { name: "Herbert Hughes Correctional Center", county: "Imperial" },
    { name: "Imperial Adult Regional Facility", county: "Imperial" },
    { name: "Imperial County Oren Fox Detention Facility", county: "Imperial" },
    { name: "Inyo County Jail", county: "Inyo" },
    { name: "Kern County Central Receiving Facility", county: "Kern" },
    { name: "Lerdo Justice Facility", county: "Kern" },
    { name: "Lerdo Maximum/Medium Security Facility", county: "Kern" },
    { name: "Lerdo Pre-Trial Facility", county: "Kern" },
    { name: "Kings County Jail", county: "Kings" },
    { name: "Lake County Hill Road Facility", county: "Lake" },
    { name: "Lassen County Adult Detention Facility", county: "Lassen" },
    { name: "Los Angeles Century Regional Detention Facility", county: "Los Angeles" },
    { name: "Los Angeles Men's Central Jail", county: "Los Angeles" },
    { name: "Los Angeles North County Correctional Facility", county: "Los Angeles" },
    { name: "Los Angeles Pitchess Detention Center East Facility", county: "Los Angeles" },
    { name: "Los Angeles Pitchess North Facility", county: "Los Angeles" },
    { name: "Los Angeles Pitchess South Facility", county: "Los Angeles" },
    { name: "Los Angeles Twin Towers Correctional Facility", county: "Los Angeles" },
    { name: "Madera Adult Correctional Facility", county: "Madera" },
    { name: "Marin County Jail", county: "Marin" },
    { name: "Mariposa County Adult Detention Facility", county: "Mariposa" },
    { name: "Mendocino Adult Detention Facility", county: "Mendocino" },
    { name: "John Latorraca Correctional Center", county: "Merced" },
    { name: "Merced County Jail", county: "Merced" },
    { name: "Modoc County Jail", county: "Modoc" },
    { name: "Mono County Jail", county: "Mono" },
    { name: "Monterey County Jail", county: "Monterey" },
    { name: "Monterey County Rehabilitation Facility", county: "Monterey" },
    { name: "Napa County Jail", county: "Napa" },
    { name: "Wayne Brown Correctional Facility", county: "Nevada" },
    { name: "Orange County Intake Release Center", county: "Orange" },
    { name: "James A. Musick Facility", county: "Orange" },
    { name: "Orange County Men's Jail", county: "Orange" },
    { name: "Orange County Women's Jail", county: "Orange" },
    { name: "Orange County Theo Lacy Jail", county: "Orange" },
    { name: "Placer County Main Jail", county: "Placer" },
    { name: "South Placer Minimum Security Jail", county: "Placer" },
    { name: "South Placer Jail", county: "Placer" },
    { name: "Plumas County Jail", county: "Plumas" },
    { name: "Blythe Jail", county: "Riverside" },
    { name: "Indio Jail", county: "Riverside" },
    { name: "Larry D. Smith Correctional Facility", county: "Riverside" },
    { name: "Robert Presley Detention Center", county: "Riverside" },
    { name: "Southwest Detention Center", county: "Riverside" },
    { name: "Rio Cosumnes Correctional Center", county: "Sacramento" },
    { name: "Sacramento County Main Jail", county: "Sacramento" },
    { name: "San Benito Adult Detention Center", county: "San Benito" },
    { name: "San Bernardino Central Detention Center", county: "San Bernardino" },
    { name: "Glen Helen Rehabilitation Center", county: "San Bernardino" },
    { name: "High Desert Detention Center", county: "San Bernardino" },
    { name: "West Valley Detention Center", county: "San Bernardino" },
    { name: "East Mesa Reentry Facility", county: "San Diego" },
    { name: "San Diego County Facility#8", county: "San Diego" },
    { name: "George Bailey Detention Facility", county: "San Diego" },
    { name: "Las Colinas Women's Detention Facility", county: "San Diego" },
    { name: "San Diego Central Jail", county: "San Diego" },
    { name: "South Bay Detention Facility", county: "San Diego" },
    { name: "Vista Detention Facility", county: "San Diego" },
    { name: "San Diego Work Furlough And Residential Reentry Center", county: "San Diego" },
    { name: "San Francisco County Jail#2", county: "San Francisco" },
    { name: "San Francisco County Jail#4", county: "San Francisco" },
    { name: "San Francisco County Jail#5", county: "San Francisco" },
    { name: "John J. Zunino Facility", county: "San Joaquin" },
    { name: "San Joaquin County Honor Farm", county: "San Joaquin" },
    { name: "San Luis Obispo County Jail", county: "San Luis Obispo" },
    { name: "San Luis Obispo Honor Farm", county: "San Luis Obispo" },
    { name: "Maguire Correctional Facility", county: "San Mateo" },
    { name: "Maple Street Correctional Facility", county: "San Mateo" },
    { name: "Men's & Women's Transitional Facilities", county: "San Mateo" },
    { name: "Santa Barbara Medium Security Facility", county: "Santa Barbara" },
    { name: "Santa Barbara County Main Jail", county: "Santa Barbara" },
    { name: "Santa Clara County Elmwood Complex - Men's Facility", county: "Santa Clara" },
    { name: "Santa Clara County Elmwood Complex - Women's Facility", county: "Santa Clara" },
    { name: "Santa Clara County Main Jail", county: "Santa Clara" },
    { name: "Santa Cruz Blaine Street Facility", county: "Santa Cruz" },
    { name: "Santa Cruz Main Jail", county: "Santa Cruz" },
    { name: "Santa Cruz Rountree Medium Facility", county: "Santa Cruz" },
    { name: "Shasta County Main Jail", county: "Shasta" },
    { name: "Siskiyou County Jail", county: "Siskiyou" },
    { name: "Claybank Facility", county: "Solano" },
    { name: "Solano County Justice Center", county: "Solano" },
    { name: "Stanton Correctional Facility", county: "Solano" },
    { name: "Sonoma County Main Adult Detention Facility", county: "Sonoma" },
    { name: "Sonoma County North County Detention Facility", county: "Sonoma" },
    { name: "Stanislaus County Public Safety Center", county: "Stanislaus" },
    { name: "Stanislaus County Public Safety Center Units 1 & 2", county: "Stanislaus" },
    { name: "Stanislaus County REACT Center", county: "Stanislaus" },
    { name: "Sutter County Jail", county: "Sutter" },
    { name: "Tehama County Jail", county: "Tehama" },
    { name: "Trinity County Detention Facility", county: "Trinity" },
    { name: "Bob Wiley Detention Facility", county: "Tulare" },
    { name: "Tulare County Men's Correctional Facility", county: "Tulare" },
    { name: "Tulare County Pre-Trial Facility", county: "Tulare" },
    { name: "Tulare County Jail", county: "Tulare" },
    { name: "Tuolumne County Jail", county: "Tuolumne" },
    { name: "Todd Road Jail", county: "Ventura" },
    { name: "Ventura County Main Jail", county: "Ventura" },
    { name: "Monroe Detention Center", county: "Yolo" },
    { name: "Walter J. Leinberger Memorial Center", county: "Yolo" },
    { name: "Yuba County Jail", county: "Yuba" }
  ];
  